// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhhtyzhpzmcnqohqjfro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoaHR5emhwem1jbnFvaHFqZnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTExNzcsImV4cCI6MjA3Mzc4NzE3N30.Z0sCEf-ZE2QH5s3lxOCZOBK0ytUFh9pMmPk8N4YSimk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});