// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhvlzogammdsoqgxcwka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVodmx6b2dhbW1kc29xZ3hjd2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDYwMjgsImV4cCI6MjA3NDAyMjAyOH0.n9R8LXT1xwg7Mcs4NQCbhs1ulNMpJF_LJpUiHgoaeeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});